apiVersion: gcp.resourcepacks.crossplane.io/v1alpha1
kind: MLCluster
metadata:
  name: test
spec:
  locations:
    - us-central1-a
  providerRef:
    name: gcp-provider
  gpuDiskSizeGb: 30
  gpuAccelerators:
    - acceleratorType: nvidia-tesla-p4
      acceleratorCount: 2
  cpuDiskSizeGb: 30
  cpuMachineType: n1-standard-4
  cpuMaxCount: 3