---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: mlclusters.gcp.resourcepacks.crossplane.io
spec:
  preserveUnknownFields: true
  group: gcp.resourcepacks.crossplane.io
  names:
    kind: MLCluster
    listKind: MLClusterList
    plural: mlclusters
    singular: mlcluster
  scope: Cluster
  subresources:
    status: {}
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
